name = "pakistan-website-builder-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

# Environment variables
[env.production.vars]
NEXT_PUBLIC_API_URL = "https://your-railway-backend.railway.app"
NEXT_PUBLIC_APP_URL = "https://your-frontend.pages.dev"
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_live_your-stripe-publishable-key"

[env.development.vars]
NEXT_PUBLIC_API_URL = "http://localhost:3001"
NEXT_PUBLIC_APP_URL = "http://localhost:3000"
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_your-stripe-publishable-key"

# Build configuration
[build]
command = "npm run build"

# Routes
routes = [
  { pattern = "pakistanbuilder.com/*", zone_name = "pakistanbuilder.com" }
]

# Custom domains (optional)
# [[env.production.routes]]
# pattern = "your-domain.com/*"
# zone_name = "your-domain.com"
