name = "pakistan-website-builder-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

# Environment variables
[env.production.vars]
NEXT_PUBLIC_API_URL = "https://api.pakistanbuilder.com/v1"
NEXT_PUBLIC_APP_URL = "https://pakistan-builder.pages.dev"

[env.development.vars]
NEXT_PUBLIC_API_URL = "http://localhost:8787/v1"
NEXT_PUBLIC_APP_URL = "http://localhost:3000"

# Build configuration
[build]
command = "npm run build"

# Routes
routes = [
  { pattern = "pakistanbuilder.com/*", zone_name = "pakistanbuilder.com" }
]
