{
  "name": "pakistan-builder",
  "compatibility_date": "2024-01-01",
  "pages_build_output_dir": ".next",
  "env": {
    "NEXT_PUBLIC_API_URL": "https://pakistan-builder-backend.up.railway.app/v1",
    "NEXT_PUBLIC_APP_URL": "https://pakistan-builder.pages.dev"
  }
}
