# Cloudflare Pages configuration for Next.js
[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "22"
NPM_VERSION = "10"

# Use @cloudflare/next-on-pages for Next.js support
compatibility_date = "2024-01-01"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "origin-when-cross-origin"
