name = "site-router"
main = "src/workers/site-router.ts"
compatibility_date = "2024-01-01"

# Routes for user sites
routes = [
  { pattern = "*.pakistanbuilder.com/*", zone_name = "pakistanbuilder.com" }
]

# R2 bucket for published sites
[[r2_buckets]]
binding = "SITES_BUCKET"
bucket_name = "pakistan-builder-published-sites"

# Environment variables
[env.production.vars]
REDIS_REST_URL = "your-upstash-redis-url"
REDIS_REST_TOKEN = "your-upstash-redis-token"
RAILWAY_API_URL = "https://your-railway-app.railway.app"

[env.development.vars]
REDIS_REST_URL = "your-dev-redis-url"
REDIS_REST_TOKEN = "your-dev-redis-token"
RAILWAY_API_URL = "http://localhost:3005"
