// Centralized icon exports for the website builder
// This file provides a single source of truth for all icons used in the application

// Feather Icons (Fi) - Primary icon library
export {
  // Basic UI
  FiX as X,
  FiCheck as Check,
  FiChevronDown as ChevronDown,
  FiChevronUp as ChevronUp,
  FiChevronLeft as ChevronLeft,
  FiChevronRight as ChevronRight,
  FiPlus as Plus,
  FiMinus as Minus,
  FiEdit as Edit,
  FiTrash2 as Trash2,
  FiSave as Save,
  FiCopy as Copy,
  FiDownload as Download,
  FiUpload as Upload,
  FiSearch as Search,
  FiFilter as Filter,
  FiSettings as Settings,
  FiMenu as Menu,
  FiMoreHorizontal as MoreHorizontal,
  FiMoreVertical as MoreVertical,

  // Navigation
  FiHome as Home,
  FiUser as User,
  FiUsers as Users,
  FiMail as Mail,
  FiPhone as Phone,
  FiGlobe as Globe,
  FiMapPin as MapPin,
  FiCalendar as Calendar,
  FiClock as Clock,
  FiEye as Eye,
  FiEyeOff as EyeOff,
  FiLock as Lock,
  FiUnlock as Unlock,
  FiShield as Shield,

  // Media
  FiImage as Image,
  FiVideo as Video,
  FiMusic as Music,
  FiFileText as FileText,
  FiFolder as Folder,
  FiTag as Tag,

  // Actions
  FiPlay as Play,
  FiPause as Pause,
  FiRotateCcw as RotateCcw,
  FiRefreshCw as RefreshCw,
  FiZap as Zap,
  FiStar as Star,
  FiHeart as Heart,
  FiMessageCircle as MessageCircle,
  FiShare2 as Share,
  FiShare2 as Share2,
  FiArrowUp as ArrowUp,
  FiArrowDown as ArrowDown,
  FiArrowLeft as ArrowLeft,
  FiArrowRight as ArrowRight,

  // Layout
  FiLayout as Layout,
  FiLayout as LayoutDashboard,
  FiGrid as Grid,
  FiSquare as Square,
  FiLayers as Layers,
  FiMaximize2 as Maximize2,
  FiMinimize2 as Minimize2,

  // Business
  FiShoppingCart as ShoppingCart,
  FiShoppingBag as ShoppingBag,
  FiCreditCard as CreditCard,
  FiPackage as Package,
  FiTruck as Truck,
  FiDollarSign as DollarSign,

  // Status
  FiCheckCircle as CheckCircle,
  FiAlertCircle as AlertCircle,
  FiAlertTriangle as AlertTriangle,
  FiInfo as Info,
  FiLoader as Loader,

  // Tools
  FiCode as Code,
  FiDatabase as Database,
  FiBarChart as BarChart,
  FiPieChart as PieChart,
  FiTrendingUp as TrendingUp,
  FiMousePointer as MousePointer,
  FiExternalLink as ExternalLink,
  FiLink2 as Link2,
  FiActivity as Activity,
  FiMonitor as Monitor,
  FiTablet as Tablet,
  FiMessageSquare as MessageSquare,
  FiFacebook as Facebook,
  FiTwitter as Twitter,
  FiInstagram as Instagram,
  FiYoutube as Youtube,
  FiLinkedin as Linkedin,
  FiHash as Hash,
  FiLink as Link,
  FiTrendingDown as TrendingDown,
  FiSmartphone as Smartphone,
  FiAward as Award,
  FiType as Type,
  FiZoomIn as ZoomIn,
  FiZoomOut as ZoomOut,
  FiTarget as Target,
  FiPrinter as Printer,
  FiArrowUpRight as ArrowUpRight,
  FiArrowDownRight as ArrowDownRight,
  FiXCircle as XCircle,
  FiBell as Bell,
  FiKey as Key,
  FiMove as Move,
  FiFolder as FolderOpen,
  FiAlignLeft as AlignLeft,
  FiAlignCenter as AlignCenter,
  FiAlignRight as AlignRight,
  FiAlignJustify as AlignJustify,
  FiList as List,
  FiFile as File,
  FiLogOut as LogOut,
  FiChevronDown as ChevronDownIcon,
  FiSearch as SearchIcon,
  FiCheck as CheckIcon,
  FiChevronRight as ChevronRightIcon,
  FiCircle as CircleIcon,
  FiX as XIcon,
  FiMinus as MinusIcon,
  FiChevronLeft as ChevronLeftIcon,
  FiMoreHorizontal as MoreHorizontalIcon,
  FiChevronUp as ChevronUpIcon,
  FiMoon as Moon,
  FiSun as Sun,
  FiNavigation as Navigation,
  FiThumbsUp as ThumbsUp,
  FiBookmark as Bookmark,
  FiVolume2 as Volume2,
  FiVolumeX as VolumeX,
  FiMic as Mic,
  FiMicOff as MicOff,
  FiHeadphones as Headphones,
  FiMessageCircle as Quote,
  FiUserPlus as UserPlus,
  FiThumbsDown as ThumbsDown,
  FiFlag as Flag,
  FiClock as Timer,
  FiLoader as Loader2,
  FiGitBranch as GitCompare,
} from 'react-icons/fi'

// Material Design Icons (Md) - Fallback for missing Feather icons
export {
  MdAutoAwesome as Sparkles,
  MdWorkspacePremium as Crown,
  MdBusiness as Building2,
  MdDashboard as Blocks,
  MdPalette as Palette,
  MdLightbulb as Lightbulb,
  MdCompare as Compare,
  MdImage as Images,
  MdGrid3X3 as Grid3X3,
  MdStickyNote2 as StickyNote,
  MdStickyNote2 as ScrollText,
  MdBuild as Building,
  MdBarChart as BarChart3,
  MdScience as TestTube,
  MdSmartToy as Bot,
  MdPayment as Banknote,
  MdGroup as Group,
  MdUndo as Undo,
  MdRedo as Redo,
  MdLanguage as Languages,
  MdDragIndicator as GripVertical,
  MdDragIndicator as GripVerticalIcon,
  MdSpaceBar as Ruler,
  MdSortByAlpha as SortAsc,
  MdSortByAlpha as SortDesc,
  MdViewSidebar as PanelLeftIcon,
  MdMilitaryTech as Medal,
  MdRocket as Rocket,
  MdDiamond as Diamond,
  MdSend as Send,
  MdWallet as Wallet,
  MdTune as SlidersHorizontal,
  MdPsychology as Brain,
  MdAutoFixHigh as Wand2,
  MdCallSplit as Ungroup,
  MdChevronLeft as PanelLeftClose,
  MdChevronRight as PanelLeftOpen,
} from 'react-icons/md'

// Bootstrap Icons (Bs) - Additional fallbacks
export {
  BsTiktok as TikTok,
  BsPinterest as Pinterest,
  BsSnapchat as Snapchat,
  BsTrophy as Trophy,
} from 'react-icons/bs'

// Helper function to get icon component by name
export const getIcon = (iconName: string): any => {
  // This is a placeholder function - components should import icons directly
  // For now, return null to avoid runtime errors
  console.warn(`getIcon function called with "${iconName}" - please import icons directly from @/lib/icons`)
  return null
}

// Note: Wildcard exports removed to prevent conflicts with named exports